server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index dashboard_topscorers.html;

  location / {
    try_files $uri /dashboard_topscorers.html;
  }

  location /api/ {
    proxy_pass http://topscorers-backend:8000/api/;
  }
}
