# k8s/deployment-frontend.yaml (ajouts marqués par ⬅)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topscorers-frontend
  namespace: topscorers
spec:
  replicas: 1
  selector:
    matchLabels: { app: topscorers-frontend }
  template:
    metadata:
      labels: { app: topscorers-frontend }
    spec:
      containers:
        - name: web
          image: ghcr.io/drokenhorisk/topscorers-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
            - name: nginx-conf                       # ⬅
              mountPath: /etc/nginx/conf.d           # ⬅ (remplace tout le dossier conf.d)
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: topscorers-data
        - name: nginx-conf                           # ⬅
          configMap:
            name: topscorers-frontend-nginx
            items:
              - key: default.conf
                path: default.conf
