apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: topscorers-ingress
  namespace: topscorers
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - topscorers.example.com
    secretName: topscorers-tls # si tu as déjà un secret TLS (sinon laisse tomber la section tls)
  rules:
  - host: topscorers.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: topscorers-frontend
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: topscorers-backend
            port:
              number: 8080
