apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: topscorers-ingress
  namespace: topscorers
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: topscorers-frontend
            port:
              number: 8080
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: topscorers-backend
            port:
              number: 8080
