#k8s/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topscorers-data
  namespace: topscorers
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
