{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "topscorers.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "topscorers.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - {{ if $host.host }}host: {{ $host.host | quote }}{{ end }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "topscorers.fullname" $ }}-backend
                port:
                  number: {{ $.Values.service.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "topscorers.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.service.frontend.port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
