apiVersion: v1
kind: Secret
metadata:
name: tops-secrets
namespace: {{ .Values.namespace }}
type: Opaque
data:
TOPS_EMAIL: {{ .Values.secretRefs.tops.email | b64enc }}
TOPS_PASSWORD: {{ .Values.secretRefs.tops.password | b64enc }}