apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topscorers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/drokenhorisk/topscorers-dashboard'
    targetRevision: feat/k8s-argocd    # <-- ICI !
    path: k8s                          # <-- dossier qui existe dans le repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: topscorers
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
